### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by sdellava** [TheJoin95/Register.it-Dynamic-DNS-Updater#8]
Hi! I've just installed the required component and I get this error:

`
sudo node index.js --username=XXXXXX --password=YYYYYY --domain=ZZZZZZ --name=QQQQQ --value=AA.BB.CC.DD --ttl=TTL_>_600 --type=A
(node:5623) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0906/151051.091243:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/sdellava/Register.it-Dynamic-DNS-Updater/node/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)
    at Interface.helper_js_1.helper.addEventListener (/home/sdellava/Register.it-Dynamic-DNS-Updater/node/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:5623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5623) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`
Of course the values inserted in the command arguments are correct.

**Comment by TheJoin95** [comment]
Hi there, unfortunately this project is not longer maintained and its implementation might be deprecated on register website.
Please, refer to other repository or, if you are willing to, please consider to contribute and re-active this project :)

Thanks!

**Comment by sdellava** [comment]
ok, tnx!
